import { t as __exportAll } from "./rolldown-runtime_D7D4PA-g.mjs";
import "./base64-B-PsqheR_BCqhUefc.mjs";
import "./types-D1iJ3DpO_B-DMySoc.mjs";
import { n as hashString } from "./hash-DFFrkivP_B6GyA9Pb.mjs";
import "./content-refresh-D4khvC0R_Bxt0RQoB.mjs";
import "./dist_e9pyH8uL.mjs";
import "./fts-manager-DzqIBrrW_C8Ds5uQp.mjs";
import { n as SchemaRegistry } from "./registry-FV15nLge_C-lxn3gO.mjs";
import { r as uniqueInterfaceNames, t as generateTypeScript } from "./zod-generator-B5prQ5M4_D0jJDS58.mjs";
import { i as requireDb, n as apiSuccess, r as handleError } from "./error-CEGF6UZb_BSWyf8Gu.mjs";
import { r as requirePerm } from "./authorize-WxsiePzy_C95XGFDu.mjs";
//#region node_modules/emdash/dist/astro/routes/api/schema/index.mjs
var schema_exports = /* @__PURE__ */ __exportAll({
	GET: () => GET,
	prerender: () => false
});
var GET = async ({ request, locals }) => {
	const { emdash, user } = locals;
	const dbErr = requireDb(emdash?.db);
	if (dbErr) return dbErr;
	const denied = requirePerm(user, "schema:read");
	if (denied) return denied;
	try {
		const registry = new SchemaRegistry(emdash.db);
		const collections = await registry.listCollections();
		const collectionsWithFields = await Promise.all(collections.map(async (c) => {
			const fields = await registry.listFields(c.id);
			return {
				...c,
				fields
			};
		}));
		if (new URL(request.url).searchParams.get("format") === "typescript") {
			const interfaceNames = uniqueInterfaceNames(collectionsWithFields);
			const types = collectionsWithFields.map((c) => generateTypeScript(c, interfaceNames.get(c.slug))).join("\n\n");
			return new Response(`// Generated by EmDash CLI
// Do not edit manually - run \`emdash types\` to regenerate

import type { PortableTextBlock } from "emdash";

` + types, {
				status: 200,
				headers: {
					"Content-Type": "text/typescript",
					"Cache-Control": "private, no-store"
				}
			});
		}
		const schemaExport = { collections: collectionsWithFields.map((c) => ({
			slug: c.slug,
			label: c.label,
			labelSingular: c.labelSingular,
			description: c.description,
			icon: c.icon,
			supports: c.supports,
			fields: c.fields.map((f) => ({
				slug: f.slug,
				label: f.label,
				type: f.type,
				required: f.required,
				unique: f.unique,
				defaultValue: f.defaultValue,
				validation: f.validation,
				widget: f.widget,
				options: f.options
			}))
		})) };
		const version = await hashString(JSON.stringify(schemaExport));
		const response = apiSuccess({
			...schemaExport,
			version
		});
		response.headers.set("X-Schema-Version", version);
		return response;
	} catch (error) {
		return handleError(error, "Schema export failed", "SCHEMA_EXPORT_ERROR");
	}
};
//#endregion
//#region \0virtual:astro:page:node_modules/emdash/dist/astro/routes/api/schema/index@_@mjs
var page = () => schema_exports;
//#endregion
export { page };
